# Generated by Django 5.1.7 on 2025-03-14 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_remove_clientprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofileimage',
            name='client_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_image', to='house.clientprofile'),
        ),
    ]
