# Generated by Django 5.1.7 on 2025-03-14 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_alter_clientprofileimage_client_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofileimage',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='house.clientprofile'),
        ),
    ]
